### ISSUE TITLE
Build fails with an exception

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects/spring-ws-samples#2]
When I issue the command ".gradle build" from the /spring-ws-samples/airline directory using gradle version 2.8 I obtain the following exception:

FAILURE: Build failed with an exception.

*Where:
Build file '..../spring-ws-samples/airline/server/build.gradle' line: 64

*What went wrong:
Execution failed for task ':server:enhance'.

> Could not find property 'runtimeClasspath' on project: ':server';

Line 64 of the file contains:

}

task enhance {
    doLast {
    ant.taskdef( name      : 'openjpaenhancer',
        classpath : project.runtimeClasspath.asPath,
        classname : 'org.apache.openjpa.ant.PCEnhancerTask'
    )

```
ant.openjpaenhancer(
    classpath : project.runtimeClasspath.asPath)
    ant.fileset(dir: "${projectDir}/src/main/java/") {
        include(name: '**/domain/*.java')
        exclude(name: 'ServiceClass.java')
    }
}   
```

}

**Comment by gregturn** [comment]
Issue no longer relevant after moving to maven.
